#!/usr/bin/env bash
# scripts/bundle.sh — Produce a release artifact tar for supercell.
#
# Usage: scripts/bundle.sh <variant> <tag>
#   variant: "runtime" or "devkit"
#   tag:     release tag, e.g. "v2026.03.25"
#
# Outputs: ./<project>-<tag>.tar.gz or ./<project>-<tag>-devkit.tar.gz
# Exit 0 on success, non-zero on failure.

set -euo pipefail

PROJECT="supercell"
VARIANT="${1:?Usage: bundle.sh <runtime|devkit> <tag>}"
TAG="${2:?Usage: bundle.sh <runtime|devkit> <tag>}"
COMMIT="${CI_COMMIT_SHA:-$(git rev-parse HEAD)}"
SHORT_SHA="${CI_COMMIT_SHORT_SHA:-$(git rev-parse --short HEAD)}"
PIPELINE_URL="${CI_PIPELINE_URL:-local}"
REGISTRY="${CI_REGISTRY_IMAGE:-registry.gitlab.com/open-arsenal/ams-gra/hello-world-sk/sim/supercell}"
CREATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BUILDER_IMAGE_REF="${REGISTRY}/builder:${TAG}"

if [[ "$VARIANT" != "runtime" && "$VARIANT" != "devkit" ]]; then
  echo "ERROR: variant must be 'runtime' or 'devkit', got '$VARIANT'" >&2
  exit 1
fi

if [[ "$VARIANT" == "devkit" ]]; then
  BUNDLE_DIR="${PROJECT}-${TAG}-devkit"
  OUTPUT="${BUNDLE_DIR}.tar.gz"
else
  BUNDLE_DIR="${PROJECT}-${TAG}"
  OUTPUT="${BUNDLE_DIR}.tar.gz"
fi

echo "=== Bundling ${PROJECT} ${TAG} (${VARIANT}) ==="

require_file() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "ERROR: required file missing: $path" >&2
    exit 1
  fi
}

set_compose_image() {
  local path="$1"
  sed -i -E 's#^([[:space:]]*image:[[:space:]]*[^[:space:]#]+):latest#\1:'"${TAG}"'#' "$path"
}

# Clean
rm -rf "$BUNDLE_DIR" "$OUTPUT"
mkdir -p "${BUNDLE_DIR}/images"

# ── Save container images ─────────────────────────────────────────────────────
echo "Saving runtime images..."
buildah push "${REGISTRY}:${TAG}" "docker-archive:${BUNDLE_DIR}/images/${PROJECT}-${TAG}.tar:${REGISTRY}:${TAG}"

buildah push "${REGISTRY}/jsbsim:${TAG}" "docker-archive:${BUNDLE_DIR}/images/${PROJECT}-jsbsim-${TAG}.tar:${REGISTRY}/jsbsim:${TAG}"

if [[ "$VARIANT" == "devkit" ]]; then
  echo "Saving builder images..."
  buildah push "${REGISTRY}/builder:${TAG}" "docker-archive:${BUNDLE_DIR}/images/${PROJECT}-builder-${TAG}.tar:${REGISTRY}/builder:${TAG}"
fi

# ── Copy compose, config ──────────────────────────────────────────────────────
cp compose.yaml "${BUNDLE_DIR}/compose.yaml"
set_compose_image "${BUNDLE_DIR}/compose.yaml"
cp env.example "${BUNDLE_DIR}/env.example"
cp -r config "${BUNDLE_DIR}/config"

# Copy jsbsim/ (JSBSim Containerfile + patches) — required for LGPL compliance
cp -r jsbsim "${BUNDLE_DIR}/jsbsim"

# ── Assemble LICENSE/LICENSES/ and sboms/ directories ─────────────────────────
mkdir -p "${BUNDLE_DIR}/LICENSES" "${BUNDLE_DIR}/sboms"

# Required contract files
require_file LICENSE
require_file LICENSES/jsbsim/LICENSE
require_file LICENSES/jsbsim/README.md
require_file THIRD_PARTY_LICENSES.html

# Project license at top-level
cp LICENSE "${BUNDLE_DIR}/LICENSE"

# Non-package-manager dependency licenses (e.g., jsbsim/)
cp -r LICENSES/jsbsim "${BUNDLE_DIR}/LICENSES/jsbsim"

# Auto-generated third-party license report under LICENSES/
cp THIRD_PARTY_LICENSES.html "${BUNDLE_DIR}/LICENSES/THIRD_PARTY_LICENSES.html"

# CycloneDX SBOMs (generated by CI sbom stage)
require_file sbom-runtime.cdx.json
cp sbom-runtime.cdx.json "${BUNDLE_DIR}/sboms/${PROJECT}-${TAG}-runtime.cdx.json"

# Additional image SBOM (jsbsim)
require_file sbom-jsbsim.cdx.json
cp sbom-jsbsim.cdx.json "${BUNDLE_DIR}/sboms/${PROJECT}-${TAG}-jsbsim.cdx.json"

if [[ "$VARIANT" == "devkit" ]]; then
  require_file sbom-builder.cdx.json
  cp sbom-builder.cdx.json "${BUNDLE_DIR}/sboms/${PROJECT}-${TAG}-builder.cdx.json"
fi

# ── Devkit extras ─────────────────────────────────────────────────────────────
if [[ "$VARIANT" == "devkit" ]]; then
  echo "Archiving source..."
  mkdir -p "${BUNDLE_DIR}/source"
  git archive --format=tar --prefix="${PROJECT}-${TAG}-src/" HEAD \
    | gzip -n > "${BUNDLE_DIR}/source/${PROJECT}-${TAG}-src.tar.gz"

  cp compose.dev.yaml "${BUNDLE_DIR}/compose.dev.yaml"
  set_compose_image "${BUNDLE_DIR}/compose.dev.yaml"
  cp compose.build.yaml "${BUNDLE_DIR}/compose.build.yaml"
fi

# ── Generate manifest.json ────────────────────────────────────────────────────
jq -n \
  --arg project "$PROJECT" \
  --arg tag "$TAG" \
  --arg commit "$COMMIT" \
  --arg pipeline_url "$PIPELINE_URL" \
  --arg created_at "$CREATED_AT" \
  --arg variant "$VARIANT" \
  --arg registry "$REGISTRY" \
  --slurpfile ports ports.json \
  --slurpfile deps dependencies.json \
  '{
    project: $project,
    tag: $tag,
    commit: $commit,
    pipeline_url: $pipeline_url,
    created_at: $created_at,
    variant: $variant,
    license: "Apache-2.0",
    images: [
      {
        name: $project,
        tag: $tag,
        registry: $registry,
        file: "images/\($project)-\($tag).tar"
      },
      {
        name: "\($project)-jsbsim",
        tag: $tag,
        registry: "\($registry)/jsbsim",
        file: "images/\($project)-jsbsim-\($tag).tar"
      }
    ],
    dependencies: $deps[0],
    ports: $ports[0]
  }' > "${BUNDLE_DIR}/manifest.json"

extract_rustdoc() {
  local container_id=""

  if ! container_id=$(buildah from "${BUILDER_IMAGE_REF}"); then
    echo "ERROR: failed to create extraction container from ${BUILDER_IMAGE_REF}" >&2
    exit 1
  fi

  mkdir -p "${BUNDLE_DIR}/docs/rustdoc"
  if ! buildah run "$container_id" -- tar cf - -C /build/target doc | tar xf - -C "${BUNDLE_DIR}/docs/rustdoc" --strip-components=1; then
    buildah rm "$container_id" >/dev/null 2>&1 || true
    echo "ERROR: failed to extract /build/target/doc from ${BUILDER_IMAGE_REF}" >&2
    exit 1
  fi

  buildah rm "$container_id" >/dev/null 2>&1 || true
}

echo "Extracting rustdoc..."
extract_rustdoc

# ── Generate SHA256SUMS ──────────────────────────────────────────────────────
echo "Generating SHA256SUMS..."
(cd "$BUNDLE_DIR" && find . -type f ! -name SHA256SUMS ! -name manifest.json -print0 \
  | sort -z \
  | xargs -0 sha256sum > SHA256SUMS)

# ── Create final tar ─────────────────────────────────────────────────────────
echo "Creating ${OUTPUT}..."
tar czf "$OUTPUT" "$BUNDLE_DIR"
rm -rf "$BUNDLE_DIR"

echo "=== Done: ${OUTPUT} ==="
